from __future__ import annotations

import os
import re
import json
import platform
import subprocess
import sys
from pathlib import Path
from datetime import datetime, timezone

import requests

# Cloud API (used for scheduling and remote access).
CLOUD_BASE_URL = os.getenv(
    "SMSGATE_BASE_URL",
    "https://api.sms-gate.app/3rdparty/v1",
).rstrip("/")

# Local Server API (used when the Android phone and laptop are on the same
# Wi-Fi/hotspot). The local API uses the legacy /message endpoint.
MODE = os.getenv("SMSGATE_MODE", "cloud").strip().lower()
LOCAL_BASE_URL = os.getenv("SMSGATE_LOCAL_URL", "").strip().rstrip("/")

LOGIN = os.getenv("SMSGATE_LOGIN", "").strip()
PASSWORD = os.getenv("SMSGATE_PASSWORD", "").strip()

# Cloud Server credentials are separate from Local Server credentials.
# Fall back to the shared credentials for backward compatibility.
CLOUD_LOGIN = os.getenv("SMSGATE_CLOUD_LOGIN", "").strip() or LOGIN
CLOUD_PASSWORD = os.getenv("SMSGATE_CLOUD_PASSWORD", "").strip() or PASSWORD


def configured() -> bool:
    if not LOGIN or not PASSWORD:
        return False
    if MODE == "local":
        return bool(LOCAL_BASE_URL)
    return bool(CLOUD_BASE_URL)


def _number(value: str) -> str:
    raw = str(value or "").strip()
    cleaned = re.sub(r"[^0-9+]", "", raw)
    if not cleaned or cleaned.startswith("++") or ("+" in cleaned[1:]):
        raise ValueError("Please provide a valid SMS phone number.")
    digits = re.sub(r"\D", "", cleaned)

    # India-friendly normalization:
    # 9501276527  -> +919501276527
    # 09501276527 -> +919501276527
    # 919501276527 -> +919501276527
    # +919501276527 stays unchanged
    if len(digits) == 10:
        digits = "91" + digits
    elif len(digits) == 11 and digits.startswith("0"):
        digits = "91" + digits[1:]
    elif len(digits) == 12 and digits.startswith("91"):
        pass
    elif len(digits) < 7:
        raise ValueError("Please provide a valid SMS phone number.")

    return "+" + digits


def _request(method: str, path: str, **kwargs):
    if not LOGIN or not PASSWORD:
        raise RuntimeError("SMSGate is not configured. Set SMSGATE_LOGIN and SMSGATE_PASSWORD in .env.")

    if MODE == "local":
        if not LOCAL_BASE_URL:
            raise RuntimeError(
                "Local SMSGate mode needs SMSGATE_LOCAL_URL, for example "
                "http://192.168.43.1:8080"
            )
        url = f"{LOCAL_BASE_URL}/{path.lstrip('/')}"
    else:
        url = f"{CLOUD_BASE_URL}/{path.lstrip('/')}"

    response = requests.request(
        method,
        url,
        auth=(LOGIN, PASSWORD),
        timeout=25,
        **kwargs,
    )

    if not response.ok:
        try:
            payload = response.json()
            detail = payload.get("message") or payload
        except Exception:
            detail = response.text or f"HTTP {response.status_code}"
        raise RuntimeError(f"SMSGate HTTP {response.status_code}: {detail}")

    try:
        return response.json()
    except Exception:
        return {}


def _local_send_payload(to: str, body: str) -> dict:
    return {
        "textMessage": {"text": body},
        "phoneNumbers": [to],
    }


def send_sms(recipient: str, message: str) -> str:
    try:
        to = _number(recipient)
    except ValueError as exc:
        return str(exc)

    body = str(message or "").strip()
    if not body:
        return "Please provide the SMS message."

    try:
        if MODE == "local":
            data = _request(
                "POST",
                "/message",
                json=_local_send_payload(to, body),
            )
        else:
            data = _request(
                "POST",
                "/messages",
                json={
                    "textMessage": {"text": body},
                    "phoneNumbers": [to],
                    "withDeliveryReport": True,
                },
            )
    except Exception as exc:
        return f"Could not send SMS through SMSGate: {exc}"

    mid = data.get("id") or data.get("messageId") or data.get("smsId") or ""
    state = data.get("state") or data.get("status") or "Queued"
    suffix = f" Message ID: {mid}." if mid else ""
    route = "phone hotspot/local server" if MODE == "local" else "SMSGate cloud"
    return f"📨 SMS submitted through {route} to {to}. Status: {state}.{suffix}"


def _write_local_sms_script(task_name: str, recipient: str, message: str) -> Path:
    """Create a one-shot script that loads NOVA's .env and sends via Local SMSGate."""
    script_dir = Path.home() / ".nova" / "sms_schedule"
    script_dir.mkdir(parents=True, exist_ok=True)
    script_path = script_dir / f"{task_name}.py"

    base_dir = Path(__file__).resolve().parent.parent
    script_body = f"""# Auto-generated by NOVA AI. One-shot scheduled SMS job.
import sys
from pathlib import Path

BASE_DIR = Path({str(base_dir)!r})
sys.path.insert(0, str(BASE_DIR))

from core import config  # loads NOVA .env
from core.smsgate_sms import send_sms

result = send_sms({recipient!r}, {message!r})
print(result)

try:
    Path(__file__).unlink(missing_ok=True)
except Exception:
    pass
"""
    script_path.write_text(script_body, encoding="utf-8")
    return script_path


def _schedule_local_windows(target_dt: datetime, task_name: str, script_path: Path) -> str:
    """Schedule a one-shot Local SMS send using Windows Task Scheduler."""
    python_exe = Path(sys.executable)
    pythonw = python_exe.parent / "pythonw.exe"
    if pythonw.exists():
        python_exe = pythonw

    xml_path = script_path.with_suffix(".xml")
    xml_content = (
        '<?xml version="1.0" encoding="UTF-16"?>\n'
        '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
        '  <RegistrationInfo><Description>NOVA AI scheduled SMS</Description></RegistrationInfo>\n'
        '  <Triggers><TimeTrigger>\n'
        f'    <StartBoundary>{target_dt.strftime("%Y-%m-%dT%H:%M:%S")}</StartBoundary>\n'
        '    <Enabled>true</Enabled>\n'
        '  </TimeTrigger></Triggers>\n'
        '  <Actions><Exec>\n'
        f'    <Command>{python_exe}</Command>\n'
        f'    <Arguments>"{script_path}"</Arguments>\n'
        '  </Exec></Actions>\n'
        '  <Settings>\n'
        '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n'
        '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n'
        '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n'
        '    <StartWhenAvailable>true</StartWhenAvailable>\n'
        '    <ExecutionTimeLimit>PT5M</ExecutionTimeLimit>\n'
        '    <Enabled>true</Enabled>\n'
        '  </Settings>\n'
        '  <Principals><Principal>\n'
        '    <LogonType>InteractiveToken</LogonType>\n'
        '    <RunLevel>LeastPrivilege</RunLevel>\n'
        '  </Principal></Principals>\n'
        '</Task>'
    )
    xml_path.write_text(xml_content, encoding="utf-16")

    flags = {}
    if platform.system() == "Windows":
        flags["creationflags"] = getattr(subprocess, "CREATE_NO_WINDOW", 0)

    result = subprocess.run(
        ["schtasks", "/Create", "/TN", task_name, "/XML", str(xml_path), "/F"],
        capture_output=True,
        text=True,
        **flags,
    )

    xml_path.unlink(missing_ok=True)

    if result.returncode != 0:
        script_path.unlink(missing_ok=True)
        return ""

    return task_name


def _scheduled_sms_store() -> Path:
    path = Path.home() / ".nova" / "sms_schedule"
    path.mkdir(parents=True, exist_ok=True)
    return path / "scheduled.json"


def list_scheduled_sms() -> list[dict]:
    store = _scheduled_sms_store()
    try:
        items = json.loads(store.read_text(encoding="utf-8"))
        if not isinstance(items, list):
            return []
    except Exception:
        return []
    now = datetime.now().astimezone()
    cleaned = []
    for item in items:
        try:
            when = datetime.fromisoformat(item["send_at"])
            if when > now:
                cleaned.append(item)
        except Exception:
            continue
    if cleaned != items:
        store.write_text(json.dumps(cleaned, indent=2), encoding="utf-8")
    return cleaned


def cancel_local_scheduled_sms(task_name: str) -> str:
    task_name = str(task_name or "").strip()
    if not task_name:
        return "Missing scheduled SMS job."
    result = subprocess.run(
        ["schtasks", "/Delete", "/TN", task_name, "/F"],
        capture_output=True, text=True,
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
    )
    if result.returncode != 0:
        return f"Could not cancel scheduled SMS: {result.stderr.strip() or result.stdout.strip()}"
    store = _scheduled_sms_store()
    items = list_scheduled_sms()
    items = [x for x in items if x.get("job") != task_name]
    store.write_text(json.dumps(items, indent=2), encoding="utf-8")
    return "Scheduled SMS cancelled."


def schedule_sms(recipient: str, message: str, send_at: datetime) -> str:
    """Schedule SMS locally; no SMSGate Cloud account is required."""
    try:
        to = _number(recipient)
    except ValueError as exc:
        return str(exc)

    body = str(message or "").strip()
    if not body:
        return "Please provide the SMS message."

    if send_at.tzinfo is None:
        send_at = send_at.astimezone()
    send_at = send_at.astimezone()

    if send_at <= datetime.now(send_at.tzinfo):
        return "The scheduled time must be in the future."

    if platform.system().lower() != "windows":
        return "Local SMS scheduling currently uses Windows Task Scheduler."

    task_name = (
        f"NOVA_SMS_{send_at.strftime('%Y%m%d_%H%M%S')}_"
        f"{abs(hash(to)) % 10000:04d}"
    )

    script_path = None
    try:
        script_path = _write_local_sms_script(task_name, to, body)
        job_id = _schedule_local_windows(send_at, task_name, script_path)
    except Exception as exc:
        if script_path:
            script_path.unlink(missing_ok=True)
        return f"Could not schedule local SMS: {exc}"

    if not job_id:
        return "Could not register the scheduled SMS with Windows Task Scheduler."

    store = _scheduled_sms_store()
    items = list_scheduled_sms()
    items.append({
        "job": job_id,
        "recipient": to,
        "message": body,
        "send_at": send_at.isoformat(),
    })
    store.write_text(json.dumps(items, indent=2), encoding="utf-8")

    local_time = send_at.strftime("%d %b %Y, %I:%M %p %Z")
    return (
        f"⏰ SMS scheduled locally for {local_time} to {to}. "
        f"Route: Vivo hotspot / SMSGate Local Server. Job: {job_id}."
    )

def _request_cloud(method: str, path: str, **kwargs):
    if not CLOUD_LOGIN or not CLOUD_PASSWORD or not CLOUD_BASE_URL:
        raise RuntimeError(
            "SMSGate Cloud is not configured. Turn on Cloud Server in SMSGate, "
            "get the generated Cloud username/password, and set "
            "SMSGATE_CLOUD_LOGIN and SMSGATE_CLOUD_PASSWORD in .env."
        )

    response = requests.request(
        method,
        f"{CLOUD_BASE_URL}/{path.lstrip('/')}",
        auth=(CLOUD_LOGIN, CLOUD_PASSWORD),
        timeout=25,
        **kwargs,
    )

    if not response.ok:
        try:
            payload = response.json()
            detail = payload.get("message") or payload
        except Exception:
            detail = response.text or f"HTTP {response.status_code}"
        raise RuntimeError(f"SMSGate Cloud HTTP {response.status_code}: {detail}")

    try:
        return response.json()
    except Exception:
        return {}


def read_messages(limit: int = 20) -> str:
    try:
        data = _request(
            "GET",
            "/messages",
            params={
                "direction": "received",
                "order": "desc",
                "limit": max(1, min(int(limit), 100)),
            },
        )
    except Exception as exc:
        return f"Could not read SMS through SMSGate: {exc}"

    items = data.get("data") if isinstance(data, dict) else None
    if not items:
        return "No received SMS messages found in SMSGate."

    lines = ["📱 Recent SMS messages:"]
    for item in items:
        sender = item.get("sender") or item.get("phoneNumber") or "Unknown"
        text = item.get("message") or item.get("text") or ""
        when = item.get("receivedAt") or item.get("createdAt") or ""
        lines.append(f"• {sender}: {text} [{when}]")
    return "\n".join(lines)


def cancel_message(message_id: str) -> str:
    mid = str(message_id or "").strip()
    if not mid:
        return "Please provide the SMS message ID to cancel."

    try:
        data = _request_cloud("DELETE", f"/messages/{mid}")
    except Exception as exc:
        return f"Could not cancel SMS through SMSGate Cloud: {exc}"

    state = data.get("state") or data.get("status") or "Cancellation requested"
    return f"🗑️ SMS cancellation requested for {mid}. Status: {state}."
